Milestone2 -  Create Components and Store
anewman15/bookstore-react pull request #2
Opened 2021-02-26 13:29 UTC by anewman15

2021-03-01 13:45 UTC, mikenath223 requested changes
### Hello Team 👋

**You've obviously done pretty well here trying your best to follow most of the requirements. 👌**

However, let's make a couple of changes.

- Please refer to comments on the code.

### **STATUS: CHANGES REQUESTED** 👷‍♂️

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

2021-03-01 13:49 UTC, mikenath223 commented on src/containers/BooksList.js
> +export default BooksList;
- [ ] Kindly connect this component to the Redux store using mapStateToProps to retrieve book objects from the store.
- [ ] Also, please ensure that a book object is passed as a prop to each Book component. So consider mapping through the book array retrieved from the store.

2021-03-01 13:50 UTC, mikenath223 commented
- [ ] In `src/reducers/index.js`, kindly combine app specific reducers.

2021-03-01 14:38 UTC, visva-dev commented
@mikenath223  Thank you for the review, but the changes that you requested are not from this milestone but from milestone 3 which we are working on right now.

2021-03-01 17:45 UTC, teekaytech requested changes
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__You've made laudable progress in this milestone. 
However, some changes are required before it can be approved.__

_Kindly note that most of the required changes by the previous reviewer should be made in milestone 2. Please check my comments below and fix them as appropriate._

**[ REQUIRED CHANGES ]**

- [ ] The `src/reducers/index.js` cannot be empty: it should combine app-specific reducers ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone2/ReducxReducers/CombinesAppReducers.png) from [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/44896827/)). The content might be similar to the snippet below: 
```JavaScript
// src/reducers/index.js

import { combineReducers } from 'redux'
import books from './books'

export default combineReducers({
  books
})

```
- [ ] Please check my inline comments below for other changes.



* * *
**Please make the required changes and submit another review request when you are done.**

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

2021-03-01 17:45 UTC, teekaytech commented on src/components/Book.js
> +
The `Book` component should accept **Book object** as a prop, not id, title, and category ([screenshot from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone2/Book/AccceptBookObjectAsProp.png))

2021-03-01 17:45 UTC, teekaytech commented on src/containers/BooksForm.js
> +  // };
All commented blocks of code should be removed.

2021-03-01 17:45 UTC, teekaytech commented on src/containers/BooksList.js
> +export default BooksList;
- The `BookList` component should be connected to Redux store and fetches books from the state ([screenshot from pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone2/BooksList/ConnetToRedux.png))

- This component should also use mapStateToProps to fetch books from the store

- Lastly, you should pass a book object as a prop to each Book component. You do not have to break down the properties of the book. Kindly pass the book object.

These are features in Milestone 2, as seen in the project specification.
![save](https://user-images.githubusercontent.com/26856491/109535590-0a96e180-7abd-11eb-9ae2-67758434e2e0.png)

2021-03-02 11:20 UTC, bellom approved these changes
## Hi Team :clap: 

**Great work making all the necessary corrections from the previous review.**

# Status: Approved 👍 

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit the project completion form.
Good luck in the next milestone :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2021-03-02 11:20 UTC, bellom commented on src/reducers/books.js
> +      id: Math.floor(Math.random() * 10000000),
### [Optional]
Kindly be aware that you can use uuidv4 to automatically generate ids. read more 👉 [npm uuid](https://www.npmjs.com/package/uuidv4)

2021-03-02 11:20 UTC, bellom commented on src/reducers/books.js
> +  books: [
### Optional 
These books should be actually be created in `src/index.js`
![image](https://user-images.githubusercontent.com/31897434/109641061-8f333f80-7b51-11eb-908b-c8aec6cdc195.png)

2021-03-02 12:04 UTC, merged